apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: hossam23/demo-app:v5
        name: demo-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
